<script setup>
import { ref } from 'vue';

const currentYear = new Date().getFullYear();

const sections = ref([
    {
        icon: 'pi-code',
        title: 'SOURCE_CODE_OWNERSHIP',
        content: 'The underlying architecture, including but not limited to the Neural Engine, Roadmap Generation Algorithms, and Vue.js Interface components, is the exclusive intellectual property of DevNexus. Unauthorized reproduction, decompilation, or "forking" of the codebase for commercial use is strictly prohibited.'
    },
    {
        icon: 'pi-user',
        title: 'USER_GENERATED_DATA',
        content: 'Roadmaps and Resumes generated by users remain the property of the user. However, DevNexus retains a perpetual, non-exclusive right to store (cache) and analyze this data anonymously to improve system accuracy and training models.'
    },
    {
        icon: 'pi-images',
        title: 'THIRD_PARTY_ASSETS',
        content: 'Certain visual assets (icons, illustrations) utilize the PrimeIcons library and open-source UI kits. These remain under their respective MIT/Apache licenses. AI-generated imagery is subject to the specific usage terms of the generative engine (e.g., Ollama/Stable Diffusion) used at the time of creation.'
    }
]);

const contactEmail = 'legal@devnexus.system';
</script>

<template>
    <div class="relative min-h-screen font-sans text-[#2c4c52] flex items-center justify-center p-4">

        <div class="absolute inset-0 z-0 pointer-events-none opacity-10"
             style="background-image: linear-gradient(#7bc5cd 1px, transparent 1px), linear-gradient(90deg, #7bc5cd 1px, transparent 1px); background-size: 30px 30px;">
        </div>

        <div class="relative z-10 w-full max-w-3xl">

            <div class="text-center mb-10">
                <div class="w-16 h-16 rounded-2xl bg-[#2c4c52] text-[#7bc5cd] flex items-center justify-center mx-auto mb-4 shadow-xl rotate-3 hover:rotate-0 transition-transform duration-500">
                    <i class="pi pi-shield text-3xl"></i>
                </div>
                <h1 class="text-3xl md:text-4xl font-black uppercase tracking-tighter text-[#2c4c52] mb-2">Intellectual Property</h1>
                <p class="font-mono text-xs font-bold text-[#4a7a82] uppercase tracking-widest">
                    System Build v2.0 &copy; {{ currentYear }} DevNexus
                </p>
            </div>

            <div class="bg-white/60 backdrop-blur-xl border border-white/60 rounded-3xl shadow-sm overflow-hidden">

                <div class="divide-y divide-[#2c4c52]/10">
                    <div v-for="section in sections" :key="section.title" class="p-8 hover:bg-white/40 transition-colors group">
                        <div class="flex gap-4">
                            <div class="mt-1">
                                <i :class="['pi text-lg text-[#2c4c52]/40 group-hover:text-[#7bc5cd] transition-colors', section.icon]"></i>
                            </div>
                            <div>
                                <h3 class="font-black text-sm uppercase text-[#2c4c52] mb-2 tracking-wide">{{ section.title }}</h3>
                                <p class="text-sm text-[#4a7a82] leading-relaxed font-medium">
                                    {{ section.content }}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="bg-[#2c4c52] p-8 text-white/80 text-center">
                    <p class="text-xs font-mono mb-4 opacity-70">
                        DevNexus respects the intellectual property rights of others.
                        If you believe your work has been infringed within our system:
                    </p>
                    <a :href="`mailto:${contactEmail}`"
                       class="inline-flex items-center gap-2 px-5 py-2 rounded-full border border-white/20 hover:bg-white/10 hover:border-white/50 transition-all text-xs font-bold uppercase tracking-wider">
                        <i class="pi pi-envelope"></i>
                        Submit DMCA Report
                    </a>
                </div>

            </div>

           

        </div>
    </div>
</template>
