<script setup>
import { ref, onMounted, onUnmounted, reactive, computed } from 'vue';
import { useRouter } from 'vue-router';

const router = useRouter();

// --- STATE ---
const activeTab = ref('SYSTEM_CORE');
const oracleResult = ref(null);
const binaryInput = ref('');
const canvasRef = ref(null);

// --- 1. MATRIX RAIN EFFECT ---
let intervalId = null;

const initMatrixRain = () => {
    const canvas = canvasRef.value;
    if (!canvas) return; // Safety check
    const ctx = canvas.getContext('2d');

    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;

    // The "Developer" Version
    const characters = '01'.split('');

    const fontSize = 16;
    const columns = canvas.width / fontSize;
    const drops = Array(Math.floor(columns)).fill(1);

    const draw = () => {
        ctx.fillStyle = 'rgba(15, 23, 25, 0.05)'; // Dark Cyan/Black fade
        ctx.fillRect(0, 0, canvas.width, canvas.height);

        ctx.fillStyle = '#7bc5cd'; // Text Color
        ctx.font = fontSize + 'px monospace';

        for (let i = 0; i < drops.length; i++) {
            const text = characters[Math.floor(Math.random() * characters.length)];
            ctx.fillText(text, i * fontSize, drops[i] * fontSize);

            if (drops[i] * fontSize > canvas.height && Math.random() > 0.975) {
                drops[i] = 0;
            }
            drops[i]++;
        }
    };
    intervalId = setInterval(draw, 33);
};

// --- 2. FUN FUNCTION: THE ORACLE ---
const archetypes = [
    { title: 'The Void Architect', desc: 'You build backend systems that are invisible yet hold the world together.', icon: 'pi pi-database' },
    { title: 'The Pixel Weaver', desc: 'You manipulate light and geometry to create stunning frontends.', icon: 'pi pi-palette' },
    { title: 'The Bug Whisperer', desc: 'Code breaks in your presence, but you know exactly how to fix it.', icon: 'pi pi-wrench' },
    { title: 'The Neural Prophet', desc: 'You speak the language of AI and data tensors.', icon: 'pi pi-bolt' },
];

const consultOracle = () => {
    oracleResult.value = { title: 'ANALYZING_AURA...', desc: 'Scanning GitHub repositories...', icon: 'pi pi-spin pi-spinner' };
    setTimeout(() => {
        const random = archetypes[Math.floor(Math.random() * archetypes.length)];
        oracleResult.value = random;
    }, 1500);
};

// --- 3. FUN FUNCTION: BINARY CIPHER ---
const binaryOutput = computed(() => {
    if (!binaryInput.value) return '';
    return binaryInput.value.split('').map(char => {
        return char.charCodeAt(0).toString(2).padStart(8, '0');
    }).join(' ');
});

// --- LIFECYCLE ---
onMounted(() => {
    initMatrixRain();
    window.addEventListener('resize', initMatrixRain);
});

onUnmounted(() => {
    if (intervalId) clearInterval(intervalId);
    window.removeEventListener('resize', initMatrixRain);
});

// --- DATA: FEATURES ---
const features = [
    { title: 'AI Roadmaps', desc: 'Dynamic learning paths generated by Ollama AI based on your career goals.', icon: 'pi pi-map' },
    { title: 'Academic Sync', desc: 'Upload university syllabus files to align industry skills with grades.', icon: 'pi pi-graduation-cap' },
    { title: 'Skill Gap Matrix', desc: 'Compare your current abilities against thousands of job descriptions.', icon: 'pi pi-chart-bar' },
];
</script>

<template>
    <div class="relative min-h-screen w-full overflow-hidden font-sans text-[#2c4c52] bg-[#0f1719]">

        <canvas ref="canvasRef" class="absolute inset-0 z-0 opacity-20 pointer-events-none"></canvas>

        <div class="absolute inset-0 z-0 bg-gradient-to-b from-transparent via-[#7bc5cd]/5 to-[#0f1719] pointer-events-none"></div>

        <div class="relative z-10 container mx-auto px-4 py-12 min-h-screen flex flex-col">

            <div class="w-full flex flex-col items-center text-center mb-12 animate-fade-in-down">

    <div class="inline-flex items-center gap-2 px-4 py-1 rounded-full bg-[#7bc5cd]/10 border border-[#7bc5cd]/30 backdrop-blur-md mb-4">
        <i class="pi pi-code text-[#7bc5cd] text-xs"></i>
        <span class="font-mono text-xs font-bold text-[#7bc5cd] tracking-[0.2em] uppercase">DevNexus_V1.0</span>
    </div>

    <h1 class="text-5xl md:text-7xl font-black text-white uppercase tracking-tighter mb-4 glow-text">
        The <span class="text-transparent bg-clip-text bg-gradient-to-r from-[#7bc5cd] to-white">Matrix</span>
    </h1>

    <p class="text-[#7bc5cd]/70 font-mono text-sm md:text-base max-w-2xl text-center">
        Decode your potential. Bridge the gap between Academic Theory and Industry Reality.
    </p>

</div>

            <div class="flex justify-center gap-4 mb-12">
                <button @click="activeTab = 'SYSTEM_CORE'"
                    class="px-6 py-3 rounded-full font-mono text-sm font-bold uppercase transition-all duration-300 border backdrop-blur-md"
                    :class="activeTab === 'SYSTEM_CORE' ? 'bg-[#7bc5cd] text-[#0f1719] border-[#7bc5cd] shadow-[0_0_20px_rgba(123,197,205,0.4)]' : 'bg-white/5 text-[#7bc5cd] border-white/10 hover:bg-white/10'">
                    System_Core
                </button>
                <button @click="activeTab = 'PLAYGROUND'"
                    class="px-6 py-3 rounded-full font-mono text-sm font-bold uppercase transition-all duration-300 border backdrop-blur-md"
                    :class="activeTab === 'PLAYGROUND' ? 'bg-[#7bc5cd] text-[#0f1719] border-[#7bc5cd] shadow-[0_0_20px_rgba(123,197,205,0.4)]' : 'bg-white/5 text-[#7bc5cd] border-white/10 hover:bg-white/10'">
                    Guest_Playground
                </button>
            </div>

            <div v-if="activeTab === 'SYSTEM_CORE'" class="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-6xl mx-auto animate-fade-in-up">
                <div v-for="(feat, i) in features" :key="i"
                     class="group relative bg-white/5 backdrop-blur-lg border border-white/10 p-8 rounded-3xl hover:bg-white/10 transition-all duration-300 hover:-translate-y-2 hover:border-[#7bc5cd]/50">
                    <div class="w-14 h-14 rounded-2xl bg-[#7bc5cd]/10 flex items-center justify-center mb-6 group-hover:bg-[#7bc5cd] transition-colors duration-300">
                        <i :class="feat.icon" class="text-2xl text-[#7bc5cd] group-hover:text-[#0f1719]"></i>
                    </div>
                    <h3 class="text-xl font-black text-white uppercase mb-2">{{ feat.title }}</h3>
                    <p class="text-[#7bc5cd]/60 text-sm leading-relaxed">{{ feat.desc }}</p>
                </div>

                <div class="md:col-span-3 mt-8 text-center p-12 bg-gradient-to-r from-[#7bc5cd]/10 to-transparent border border-[#7bc5cd]/20 rounded-3xl backdrop-blur-md">
                    <h2 class="text-2xl font-bold text-white uppercase mb-4">Ready to Jack In?</h2>
                    <button @click="router.push('/auth/login')" class="px-8 py-3 rounded-full bg-[#7bc5cd] text-[#0f1719] font-black uppercase tracking-widest hover:scale-105 transition-transform shadow-[0_0_30px_rgba(123,197,205,0.3)]">
                        Initialize User Protocol
                    </button>
                </div>
            </div>

            <div v-if="activeTab === 'PLAYGROUND'" class="grid grid-cols-1 lg:grid-cols-2 gap-8 max-w-5xl mx-auto animate-fade-in-up">

                <div class="bg-white/5 backdrop-blur-lg border border-white/10 p-8 rounded-3xl flex flex-col justify-between">
                    <div>
                        <div class="flex justify-between items-start mb-6">
                            <h3 class="text-xl font-black text-white uppercase flex items-center gap-2">
                                <i class="pi pi-eye text-[#7bc5cd]"></i> The Oracle
                            </h3>
                            <span class="text-[10px] font-mono text-[#7bc5cd]/50 border border-[#7bc5cd]/20 px-2 py-1 rounded">V1.0</span>
                        </div>
                        <p class="text-[#7bc5cd]/60 text-sm mb-8">
                            Unsure of your path? Let the algorithm analyze your digital signature and assign you a developer archetype.
                        </p>

                        <div v-if="oracleResult" class="bg-[#0f1719]/50 border border-[#7bc5cd]/20 p-6 rounded-2xl mb-6 text-center animate-pulse-once">
                            <i :class="oracleResult.icon" class="text-3xl text-[#7bc5cd] mb-3 block"></i>
                            <div class="text-lg font-bold text-white uppercase mb-1">{{ oracleResult.title }}</div>
                            <div class="text-xs font-mono text-[#7bc5cd]">{{ oracleResult.desc }}</div>
                        </div>
                    </div>

                    <button @click="consultOracle" class="w-full py-3 rounded-xl border border-[#7bc5cd] text-[#7bc5cd] font-bold uppercase hover:bg-[#7bc5cd] hover:text-[#0f1719] transition-all">
                        Analyze My Aura
                    </button>
                </div>

                <div class="bg-white/5 backdrop-blur-lg border border-white/10 p-8 rounded-3xl flex flex-col justify-between">
                    <div>
                        <div class="flex justify-between items-start mb-6">
                            <h3 class="text-xl font-black text-white uppercase flex items-center gap-2">
                                <i class="pi pi-key text-[#7bc5cd]"></i> Binary Whisper
                            </h3>
                            <span class="text-[10px] font-mono text-[#7bc5cd]/50 border border-[#7bc5cd]/20 px-2 py-1 rounded">ENC_MOD</span>
                        </div>

                        <div class="space-y-4">
                            <div>
                                <label class="text-[10px] font-mono font-bold text-[#7bc5cd] uppercase block mb-1">Human Input</label>
                                <input v-model="binaryInput" type="text" placeholder="Type secret message..."
                                    class="w-full bg-[#0f1719]/50 border border-white/10 rounded-xl px-4 py-3 text-white focus:border-[#7bc5cd] focus:outline-none placeholder:text-white/20 font-mono text-sm" />
                            </div>

                            <div>
                                <label class="text-[10px] font-mono font-bold text-[#7bc5cd] uppercase block mb-1">Machine Output</label>
                                <div class="w-full h-24 bg-[#0f1719]/80 border border-white/10 rounded-xl p-4 text-[#7bc5cd] font-mono text-xs break-all overflow-y-auto shadow-inner">
                                    {{ binaryOutput || 'WAITING_FOR_INPUT...' }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </div>
</template>

<style scoped>
@keyframes fade-in-down {
    from { opacity: 0; transform: translateY(-20px); }
    to { opacity: 1; transform: translateY(0); }
}
@keyframes fade-in-up {
    from { opacity: 0; transform: translateY(20px); }
    to { opacity: 1; transform: translateY(0); }
}
.animate-fade-in-down { animation: fade-in-down 0.8s ease-out; }
.animate-fade-in-up { animation: fade-in-up 0.8s ease-out; }

.animate-pulse-once {
    animation: pulse-once 0.5s ease-out;
}
@keyframes pulse-once {
    0% { transform: scale(0.95); opacity: 0.5; }
    100% { transform: scale(1); opacity: 1; }
}

.glow-text {
    text-shadow: 0 0 20px rgba(123, 197, 205, 0.3);
}
</style>
